"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { humanize } from "@/lib/format";
import { Feedback, LoadingBlock, PageIntro, StatusBadge } from "@/components/ui";

interface Template {
  id: string;
  key: string;
  subject: string;
  html_body: string;
  text_body: string;
  version: number;
  is_active: boolean;
}

export function TemplateManager() {
  const [items, setItems] = useState<Template[]>([]);
  const [selected, setSelected] = useState<Template | null>(null);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [loading, setLoading] = useState(true);

  function load() {
    api<{ templates: Template[] }>("/admin/templates")
      .then((response) => {
        setItems(response.templates);
        setSelected((current) => current
          ? response.templates.find((item) => item.key === current.key) || response.templates[0]
          : response.templates[0]);
      })
      .catch((requestError: Error) => setError(requestError.message))
      .finally(() => setLoading(false));
  }

  useEffect(load, []);

  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!selected) return;
    setError("");
    setSuccess("");
    const form = new FormData(event.currentTarget);
    try {
      await api(`/admin/templates/${selected.key}`, {
        method: "PUT",
        body: {
          subject: form.get("subject"),
          text_body: form.get("text_body"),
          html_body: form.get("html_body"),
          is_active: form.get("is_active") === "on",
        },
      });
      setSuccess("Email template saved as a new version.");
      load();
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : "Save failed");
    }
  }

  if (loading) return <LoadingBlock label="Loading email templates" />;

  return (
    <>
      <PageIntro title="Email templates" body="Manage candidate-facing messages generated by recruitment events." />
      {error ? <Feedback tone="error">{error}</Feedback> : null}
      {success ? <Feedback tone="success">{success}</Feedback> : null}
      <div className="template-layout">
        <nav className="template-list" aria-label="Email templates">
          {items.map((item) => (
            <button className={selected?.key === item.key ? "active" : ""} onClick={() => setSelected(item)} key={item.key}>
              <span><strong>{humanize(item.key)}</strong><small>Version {item.version}</small></span>
              <StatusBadge value={item.is_active ? "Active" : "Inactive"} />
            </button>
          ))}
        </nav>
        {selected ? (
          <form className="panel template-editor" onSubmit={save} key={selected.key}>
            <div className="panel-heading"><div><h2>{humanize(selected.key)}</h2></div><code>{selected.key}</code></div>
            <label><span>Subject</span><input name="subject" defaultValue={selected.subject} required /></label>
            <label><span>Plain text body</span><textarea name="text_body" rows={10} defaultValue={selected.text_body} /></label>
            <label><span>HTML body</span><textarea name="html_body" rows={12} defaultValue={selected.html_body} /></label>
            <label className="check-field"><input type="checkbox" name="is_active" defaultChecked={selected.is_active} /><span>Template is active</span></label>
            <div className="template-variables">
              <strong>Available variables</strong>
              <code>{"{{candidate_name}}"}</code>
              <code>{"{{job_title}}"}</code>
              <code>{"{{application_status}}"}</code>
              <code>{"{{application_url}}"}</code>
            </div>
            <button className="button button-primary">Save template</button>
          </form>
        ) : null}
      </div>
    </>
  );
}
